// <auto-generated />
namespace EFCodeFirstTut.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DB_TblPostCreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_TblPostCreation));
        
        string IMigrationMetadata.Id
        {
            get { return "202302181509551_DB_Tbl-PostCreation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
